/**
 * Generated by Gas3 v1.1.0 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package incubator.spring_flex.dto {

[Bindable]
[RemoteClass(alias="incubator.spring_flex.dto.Ingredient")]
    public class Ingredient extends IngredientBase {
public function Ingredient(){
    super();
  }

}
}