/**
 * Generated by Gas3 v1.1.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR.
 */

package incubator.spring_flex.dto.enums {

    import org.granite.util.Enum;

    [Bindable]
    [RemoteClass(alias="incubator.spring_flex.dto.enums.PizzaType")]
    public class PizzaType extends Enum {

public static const CHEESY:PizzaType = new PizzaType("CHEESY", _);
public static const CLASSIC:PizzaType = new PizzaType("CLASSIC", _);
public static const PAN:PizzaType = new PizzaType("PAN", _);

function PizzaType(value:String = null, restrictor:* = null) {
            super((value || CHEESY.name), restrictor);
        }
        
        override protected function getConstants():Array {
            return constants;
        }

        public static function get constants():Array {
            return [CHEESY, CLASSIC, PAN];
        }

        public static function valueOf(name:String):PizzaType {
        	return PizzaType(CHEESY.constantOf(name));
        }
    }
}